### PR TITLE
chore: migrate general docs

### PR DESCRIPTION
**Pull request by nicktrn**
Also removed some templates/examples, but left the demo api docs.

External assets are all still where they were for now. Can pull them into this repo if needed.

I think it's looking pretty good.

/claim #1

### CODE REVIEW

**Comment by andrerfneves** [comment]
@nicktrn this is dope! Can we import the assets actually. I know this wasn't part of the ticket req (I honestly forgot about them).

**Comment by nicktrn** [comment]
No worries, all done

**Comment by andrerfneves** [comment]
Okay reviewing here.

**Comment by andrerfneves** [comment]
@nicktrn only found this one with a problem

Screenshot 2023-08-07 at 4 39 37 PM

the rest is clean. If we can resolve that one I'll merge and reward

**Comment by nicktrn** [comment]
Think it doesn't like the indented code blocks, will have a quick look how to format this without losing structure.

**Comment by nicktrn** [comment]
Turns out their components don't like empty lines..

**Pull request merged**
