### PR TITLE
Add beamable docs

### PR DESCRIPTION
**Pull request by theDevBrent**

### CODE REVIEW

**Comment by mandelmonkey** [comment]
@theDevBrent we need to change references to Zebedee as ZBD
fyi we also never right Zebedee lowercase its always uppercase ZEBEDEE, but seems like we are moving to ZBD now anyway

**Comment by theDevBrent** [comment]
Ok, I'll change all references to ZBD

**Comment by andrerfneves** [comment]
@stemperian can you review this alongside @theDevBrent and @mandelmonkey? I've noted all images are named `UntitledX`, maybe we just move to `beamable-guideX.png` or something more related? Are these images web-optimized a bit? Some seem to be quite large files. @stemperian check ImageOptim app.

**Comment by theDevBrent** [comment]
Good catch. I'll update the titles and compress the images.

**Comment by mandelmonkey** [comment]
@stemperian Are we good to merge this? beamable are asking about when we would be ready to announce with them and this is the last thing on our end before we can do that

**Pull request merged**
