### PR TITLE
Documentation revamp: migrate general API Reference endpoints from docs.zebedee.io to Mintlify codebase

### LINKED ISSUE #2: Documentation revamp: migrate general API Reference endpoints from docs.zebedee.io to Mintlify codebase
This is the sibling issue of https://github.com/andrerfneves/zbd-docs/issues/1.

We are migrating our content from our own documentation system built on docusaurus to one in Mintlify. We

We need someone to copy the contents of every one of the API Reference documents in the docs.zebedee.io THE API REFERENCE, and port over to this codebase.

Start here: https://docs.zebedee.io/api/intro

Basically, need to port over every page/endpoint from inside https://docs.zebedee.io/api/intro over to this codebase. In individual pages (as expected by Mintlifly)

The idea is to maintain the same content structure, just make it available within this new Mintlify kit/setup. The contents should be the same and use the best capabilities from Mintlify's systems

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Resolves #2
/claim #2

### CODE REVIEW

**Comment by andrerfneves** [comment]
hey @rishi-raj-jain let me know when this is ready to review!

**Comment by rishi-raj-jain** [comment]
@andrerfneves Hey yeah I'm gonna be hitting the bed now, but shall be done with this by tom!

**Comment by andrerfneves** [comment]
Sounds great @rishi-raj-jain. Looking forward to it

**Comment by rishi-raj-jain** [comment]
@andrerfneves This is ready for review.

**Comment by rishi-raj-jain** [comment]
@andrerfneves This is ready for review.

**Comment by rishi-raj-jain** [comment]
@andrerfneves This is ready for review.

**Comment by andrerfneves** [comment]
@rishi-raj-jain this looks REALLY good. I'm reviewing with my team and hoping to close + reward tomorrow!

**Comment by rishi-raj-jain** [comment]
@andrerfneves Thank you so much! Awaiting the magical $ haha.

**Comment by rishi-raj-jain** [comment]
If possible, given my effort, I'd love the price to be at $150 instead of $100. But it's fine either ways, $100 or $150 so yeah just saying.

**Comment by nicktrn** [comment]
@andrerfneves Are you not using Swagger / OpenAPI internally? Would make this a lot [easier to maintain](https://mintlify.com/docs/api-playground/openapi).

Just expose a (public) API endpoint that returns your spec and set up a workflow to pull it into this repo on a regular basis. You get automatically updating API docs for free. Even works for new endpoints with an [extra workflow step](https://mintlify.com/docs/api-playground/openapi-generation).

**Comment by nicktrn** [comment]
Just a suggestion for future reference. You've obviously done the work!

**Comment by rishi-raj-jain** [comment]
Closed by mistake! That button is streamed by GitHub 🥺

Ofc was kidding about that @nicktrn

**Comment by rishi-raj-jain** [comment]
Tomorrow is here!

**Comment by andrerfneves** [comment]
Okay I've verified this PR extensively and unfortunately found quite a few issues/discrepancies with the current existing documentation API reference available. If we can get these resolved then I can award, but as it stands there are parts that are not workable atm.


**1. Pages not loading**
These pages just break on loading. Needs to be fixed
Screenshot 2023-08-12 at 10 33 20 AM

**2. `expiresIn` field**
This one is self-explanatory.
Screenshot 2023-08-12 at 10 34 05 AM

**3. API Request tool**
One of the main things we need to ensure works 100% is the API Request testing tool. This exists on the right hand side of current documentation site. In the new site it lives in the middle, in the shape of a form module. After testing, the testing module doesn't seem to work for **MANY** endpoints. This HAS to be a config/code issue on the new docuemntation since it works 100% on the current doc portal. Below are screenshots of the ones that do not work on the new site:

Screenshot 2023-08-12 at 10 38 23 AM
Screenshot 2023-08-12 at 10 38 20 AM
Screenshot 2023-08-12 at 10 38 06 AM
Screenshot 2023-08-12 at 10 38 02 AM
Screenshot 2023-08-12 at 10 37 59 AM
Screenshot 2023-08-12 at 10 37 55 AM
Screenshot 2023-08-12 at 10 37 51 AM
Screenshot 2023-08-12 at 10 37 47 AM
Screenshot 2023-08-12 at 10 37 43 AM
Screenshot 2023-08-12 at 10 37 37 AM
Screenshot 2023-08-12 at 10 37 33 AM


Once we resolve these and ensure that the API testing kit for every one of the endpoints is working as expected, then we will be good to close this out.

I believe most of #3 is just configuration tweaks on the API testing tool for each of the pages.

Let me know if this all makes sense @rishi-raj-jain!.This is great work and we're almost complete! Just the last little bit now.

**Comment by rishi-raj-jain** [comment]
Hey @andrerfneves,

Regarding 
image

This was not added by me. This was done by @nicktrn

**Comment by andrerfneves** [comment]
Ah nice catch. Disregard that one then 🫡

**Comment by rishi-raj-jain** [comment]
@andrerfneves This is ready for review. The fix was easy: https://mintlify.com/docs/api-playground/configuration#:~:text=endpoint%20has%20a-,path,-parameter%2C%20the%20path was the one thing misconfigured in all of them.

**Comment by rishi-raj-jain** [comment]
I've also checked the documentation to not have anything which is "/:" so that the error is not repeated. Let me know if anything.

**Comment by nicktrn** [comment]
Just cleaning up after myself #5

**Comment by rishi-raj-jain** [comment]
Looks like we both just completed ZBD Docs migration!

**Comment by nicktrn** [comment]
thumbsup

**Comment by andrerfneves** [comment]
> @andrerfneves This is ready for review. The fix was easy: https://mintlify.com/docs/api-playground/configuration#:~:text=endpoint%20has%20a-,path,-parameter%2C%20the%20path was the one thing misconfigured in all of them.

Love to hear it!

**Comment by andrerfneves** [comment]
Thank you @rishi-raj-jain!! Just merged it

**Pull request merged**
